apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-success-rate
  namespace: demo
  labels:
    app: api
spec:
  metrics:
    - name: api-success-rate
      interval: 30s
      count: 2
      failureLimit: 0
      successCondition: result[0] >= 0.99
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            1 -
            (
              (sum(rate(flask_http_request_total{namespace="demo",job="api",status=~"5.."}[1m])) or vector(0))
              /
              clamp_min((sum(rate(flask_http_request_total{namespace="demo",job="api"}[1m])) or vector(0)), 0.001)
            )
